### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Bhavikapatel4591** [jusce17/rasa_form_example#1]
Hello,
Can you know which version of tensorflow should be installed ? As Iam facing the below error while running **rasa train** 

Current version of tensorflow is 2.1.1

Traceback (most recent call last):
  File "c:\users\appstekn16\anaconda3\envs\bot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\appstekn16\anaconda3\envs\bot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\appstekn16\anaconda3\envs\bot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\appstekn16\anaconda3\envs\bot\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\appstekn16\anaconda3\envs\bot\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Thanks in advance.

**Comment by jusce17** [comment]
here is  the list of all dependencies 
[requirements.txt](https://github.com/jusce17/rasa_form_example/files/5275842/requirements.txt)

**Comment by jusce17** [comment]
@Bhavikapatel4591 perhaps you can install it manually, like this

pip install gast ==0.2.2
pip install scipy==1.4.1

**Comment by Bhavikapatel4591** [comment]
@jusce17  Thanks for your prompt reply. I have verified the requirements.txt , Iam facing an error w.r.to Uvloop  as 

**RuntimeError: uvloop does not support Windows at the moment**

**Comment by jusce17** [comment]
Hey @Bhavikapatel4591  can you please do a 
pip install -r [requirements.txt](https://github.com/jusce17/rasa_form_example/files/5361920/requirements.txt)

Filed attached
